question_data = [{"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard "
                              "Mark II computer.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "All program codes have to be compiled into an executable file in order to be run. "
                              "This file can then be executed on any machine.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "Linus Torvalds created Linux and Git.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "Pointers were not used in the original C programming language; they were added later "
                              "on in C++.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "AMD created the first consumer 64-bit processor.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "hard",
                  "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of "
                              "memory.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "Linux was first created as an alternative to Windows XP.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "A Boolean value of &quot;0&quot; represents which of these words?",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers",
                  "type": "boolean",
                  "difficulty": "hard",
                  "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]}]
